DjangowithReact/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from reactfrontend.views import SampleReactView,SimpleReactView
app_name = 'djangowithreact'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('main.urls')),
    path('',SimpleReactView),
    path('profile',SampleReactView,name='profile'),
    path('accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path

from .import views
# from .utils import HelloPDFView

urlpatterns = [
    # path('a',views.SampleUserView),
    path('',views.QuestionWithExcelCreateView.as_view(),name="myapp"),
    path('profile',views.photo_list,name="photo_list"),
    path('pdf',views.GeneratePdf.as_view()),
    path('report',views.some_view),
    path('message',views.message),
    path('status',views.status),
    path('verifiedd',views.phoneVerify),
    path('verified',views.PhoneVerified,name="verified"),
    path('deregister',views.PhoneDeVerify,name="deverify"),
    path('pdfs',views.TestDocument),
    
    path('tab',views.listTabs,name="list_tab"),
    path('lession',views.listLessions,name="list_lession"),
    path("tablession/<int:tpk>",views.listTabLessions),
    path('question/<int:pk>',views.listQuestions),
    path('category',views.listCategorys),
    path('tab/<int:tpk>/<int:lpk>',views.listTabLessionQuestion,name="list_tab_question"),
    path('nlession/<int:tpk>',views.listLessionsNecessary),
    path('answer/<int:pk>',views.getAnswer,name="getanswer"),
    path('pass',views.PasswordResetWithOldPass,name="pass"),

    path('update/<int:pk>',views.QuestionUpdateView.as_view()),
    path('user',views.UserUpdateView.as_view(),name="userupdate"),
    path('add/lession',views.LessionCreateView.as_view(),name="createlession"),
    path('add/question',views.QuestionWithExcelCreateView.as_view(),name="createquestion"),
    path('add/question/<int:tpk>/<int:lpk>',views.QuestionWithExcelCreateView.as_view(),name="createquestion"),
    path('add/category',views.CategoryCreateView.as_view(),name="createcategory"),
    path('add/tab',views.TabCreateView.as_view(),name="createtab"),

    
]

main/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.contrib.auth.models import User,AbstractUser
# Create your models here.
class User(AbstractUser):
    phone = models.CharField(max_length=16,null=True,blank=True)
    isVerifiedMobile = models.BooleanField(default=False)
class Category(models.Model):
    useremail = models.EmailField(max_length=254,null=False)
    name = models.CharField(max_length=10,unique=True)
    description = models.CharField(max_length=250)

    def __str__(self):
        return self.name 
    def get_absolute_url(self):
        return reverse("createcategory")


class Tab(models.Model):
    useremail = models.EmailField(max_length=254,null=False)
    name = models.CharField(max_length=50,null=False,blank=False)
    description = models.TextField(blank=True,null=True)
    
    class Meta:
        unique_together = ['name']
        

    def __str__(self):
        return '{0} - {1}'.format(self.pk,self.name)

class Lession(models.Model):
    tabs = models.ManyToManyField(Tab)
    name =  models.CharField(max_length=250)  
    description = models.TextField(null=True,blank=True)
    division = models.ForeignKey(Category,on_delete=models.RESTRICT)
    
    @property
    def getdivision(self):
        return self.division.name
    @property
    def getqnscount(self):
        return Question.objects.filter(lession__exact=self).count()   
    class Meta:    
        unique_together = ['name','division']
    def __str__(self):
        return f'{self.name} || {self.id}'
    def get_absolute_url(self):
        return reverse("createlession")
        
class Question(models.Model):
    
    tab = models.ManyToManyField(Tab)
    lession = models.ManyToManyField(Lession)
    question = models.TextField(blank=True)
    answer = models.TextField(blank=True)
    

    class Meta:
        unique_together=['question','answer']
        pass
    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse("createquestion")
        
        
class Photo(models.Model):
    file = models.ImageField()
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'      

main/forms.py
from django.forms import ModelForm,Textarea,Form,ModelMultipleChoiceField
from .models import Question,Tab,Lession,Category
from django import forms
# from django.contrib.auth.models import User
from .models import User
from django.contrib.auth.forms import PasswordChangeForm



class UserUpdateForm(ModelForm):
    def __init__(self,*args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['last_login'].widget.attrs['readonly'] = True
            self.fields['date_joined'].widget.attrs['readonly'] = True
    class Meta:
        model = User
        fields = ['username','first_name','last_name','last_login','date_joined']
    # def get_context_data(self, **kwargs):
    #     context = super(UserUpdateForm, self).get_context_data(**kwargs)
    #     print(context)
    #     return context  
  


class CustomLessionLabel(forms.ModelMultipleChoiceField):
    def label_from_instance(self, member):
        return "%s" % member.name
class QuestionForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(QuestionForm, self).__init__(*args, **kwargs)
        
        self.fields['tab'].queryset = Tab.objects.filter(
            useremail=self.request.user.email)    
        tabsquery = Tab.objects.filter(
            useremail=self.request.user.email)     
        self.fields['lession'].queryset = Lession.objects.filter(tabs__in = tabsquery).distinct()
    class Meta:
        model = Question
        widgets = {
          'question': Textarea(attrs={'rows':1, 'cols':50}),
          'answer': Textarea(attrs={'rows':1, 'cols':50}),
        }
        fields = '__all__'
    lession = CustomLessionLabel(
        queryset=None,
        widget=forms.SelectMultiple(attrs={ 'id' : 'lession' , 'class':'choices-multiple', 'style': "max-width:90%;"}),) 
    tab = CustomLessionLabel(
        queryset=None,
        widget=forms.SelectMultiple(attrs={ 'id' : 'tab' ,'class':'choices-multiple', 'style': "max-width:90%;"}),)
class LessionForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(LessionForm, self).__init__(*args, **kwargs)
        self.fields['tabs'].queryset = Tab.objects.filter(
            useremail=self.request.user.email)
        self.fields['division'].queryset = Category.objects.filter(
            useremail=self.request.user.email)
    class Meta:
        model = Lession
        # widgets = {
        #   'tabs': forms.CheckboxSelectMultiple(choices=Tab.objects.filter(useremail__exact='lali.1817129@gct.ac.in'))

        # }
        fields = '__all__'
    tabs = CustomLessionLabel(
        queryset=None,
        widget=forms.SelectMultiple(attrs={ 'id' : 'choices-multiple-remove-button' , 'style': "max-width:90%;"}),
       )
        
    division = forms.ModelChoiceField(empty_label=None,queryset=None,widget=forms.Select(attrs={ 'class' : 'form-select'})) 

from PIL import Image
from django.core.files import File
from .models import Photo



class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

main/templates/userprofile/index.html
{% extends "main/base.html" %}
{% load  static %}

	{% block title%}{{name}}
	

	 {% endblock%}
{%block content%}
{% load static%}
<script src="https://www.gstatic.com/firebasejs/6.0.2/firebase.js"></script>
	<script>


const firebaseConfig = {
  apiKey: "AIzaSyDUdoFBLJA4PPgEY89ZwZb1OMQg4SO5FOU",
  authDomain: "explore-81b2d.firebaseapp.com",
  projectId: "explore-81b2d",
  storageBucket: "explore-81b2d.appspot.com",
  messagingSenderId: "297028201215",
  appId: "1:297028201215:web:7083af8af39ed5e8dbbaca",
  measurementId: "G-K9GCZLC8KX"
};


    firebase.initializeApp(firebaseConfig);
</script>
<script src="{% static 'main/NumberAuthentication.js' %}" type="text/javascript"></script>

	<section class="py-5 my-5">
		<div class="container">
			<h1 class="mb-5">Account Settings</h1>
			<div class="bg-white shadow rounded-lg d-block d-sm-flex">
				<div class="profile-tab-nav border-right">
					<div class="p-4">
						<div class="img-circle text-center mb-3">
							<img src="{% static 'main/user2.jpg' %} " alt="Image" class="shadow">
						</div>
						<h4 class="text-center">{{user.username}}</h4>
					</div>
					<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
						<a class={% if not active == 2 %}"nav-link active" {% else %}"nav-link"{% endif %} id="account-tab" data-toggle="pill" href="#account" role="tab" aria-controls="account" aria-selected={% if not active == 2 %}"true" {% else %}"false"{% endif %}>
							<i class="fa fa-home text-center mr-1"></i> 
							Account
						</a>
						<a class={% if active == 2 %}"nav-link active" {% else %}"nav-link"{% endif %} id="password-tab" data-toggle="pill" href="#password" role="tab" aria-controls="password" aria-selected="false">
							<i class="fa fa-key text-center mr-1"></i> 
							Password
						</a>
						<a class="nav-link" id="security-tab" data-toggle="pill" href="#security" role="tab" aria-controls="security" aria-selected="false">
							<i class="fa fa-user text-center mr-1"></i> 
							Security
						</a>
						<a class="nav-link" id="application-tab" data-toggle="pill" href="#application" role="tab" aria-controls="application" aria-selected="false">
							<i class="fa fa-tv text-center mr-1"></i> 
							Application
						</a>
						<a class="nav-link" id="notification-tab" data-toggle="pill" href="#notification" role="tab" aria-controls="notification" aria-selected="false">
							<i class="fa fa-bell text-center mr-1"></i> 
							Notification
						</a>
					</div>
				</div>
				<div class="tab-content p-4 p-md-5" id="v-pills-tabContent">
					<div class={% if not active == 2 %} "tab-pane fade show active" {% else %}"tab-pane fade"{% endif %} id="account" role="tabpanel" aria-labelledby="account-tab">
						<h3 class="mb-4">Account Settings</h3>
							<div class="row">
							<div class="col-md-6">
								<div class="form-group">
								  	 <form method="post" novalidate>
  									{% csrf_token %}
 								 {% include 'main/bs4form.html' with form=form %}
								  
  								<center><button type="submit" class="btn btn-primary">Update</button></center>
								</form>
								</div>
							</div>
							

							
							</div>
						
						
					</div>
					<div class={% if active == 2 %} "tab-pane fade show active" {% else %}"tab-pane fade"{% endif %}  id="password" role="tabpanel" aria-labelledby="password-tab">
						<h3 class="mb-4">Password Settings</h3>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
								  	 <form method="post" onSubmit="posts()" novalidate action="">
  									{% csrf_token %}
 								 {% include 'main/bs4form.html' with form=form1 %}
								  
  								<center><button type="submit" class="btn btn-primary" onclick="posts()">Update</button></center>
								</form>
								<script>
								function posts(){
								$.ajax({
									type : 'POST',
									headers : { 'X-CSRFToken': "{{ csrf_token }}" },
									url : " {% url 'pass' %} ",
									data : { "{{ form1 }}"   }

								})
								}
								</script>
								</div>
							</div>
						</div>
						<div class="row">
						</div>
					</div>
					<div class="tab-pane fade" id="security" role="tabpanel" aria-labelledby="security-tab">
						<h3 class="mb-4">Security Settings</h3>
						<div class="row">
							
								{% if user.is_authenticated %}
								{% if not user.isVerifiedMobile %}
								<form class="form-control">
    								<input type="text" id="number" value="+1 555-555-5555" class="form-control">
    								<div id="recaptcha-container"></div>
    								<button class="btn-primary" type="button" onclick="phoneAuth();">SendCode</button>
								</form>
								
								<div id="otpverify" style="display:none">
								<form>
 									<input class="form-control" type="text" id="verificationCode" placeholder="Enter verification code">
   									 <button class="btn-primary" type="button" onclick="codeverify();">Verify code</button>
								</form>
								</div>
								{% else %}
								  <input  value="{{ user.phone }}" readonly>
								  <a class="btn-primary" href=" {% url 'deverify'  %} "> <button  >Deregister</button></a>
								{% endif %}
								{% endif %}
								</div>
							
					</div>
					<div class="tab-pane fade" id="application" role="tabpanel" aria-labelledby="application-tab">
						<h3 class="mb-4">Application Settings</h3>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<div class="form-check">
										<input class="form-check-input" type="checkbox" value="" id="app-check">
										<label class="form-check-label" for="app-check">
										App check
										</label>
									</div>
									<div class="form-check">
										<input class="form-check-input" type="checkbox" value="" id="defaultCheck2" >
										<label class="form-check-label" for="defaultCheck2">
										Lorem ipsum dolor sit.
										</label>
									</div>
								</div>
							</div>
						</div>
						<div>
							<button class="btn btn-primary">Update</button>
							<button class="btn btn-light">Cancel</button>
						</div>
					</div>
					<div class="tab-pane fade" id="notification" role="tabpanel" aria-labelledby="notification-tab">
						<h3 class="mb-4">Notification Settings</h3>
						<div class="form-group">
							<div class="form-check">
								<input class="form-check-input" type="checkbox" value="" id="notification1">
								<label class="form-check-label" for="notification1">
									Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum accusantium accusamus, neque cupiditate quis
								</label>
							</div>
						</div>
						<div class="form-group">
							<div class="form-check">
								<input class="form-check-input" type="checkbox" value="" id="notification2" >
								<label class="form-check-label" for="notification2">
									hic nesciunt repellat perferendis voluptatum totam porro eligendi.
								</label>
							</div>
						</div>
						<div class="form-group">
							<div class="form-check">
								<input class="form-check-input" type="checkbox" value="" id="notification3" >
								<label class="form-check-label" for="notification3">
									commodi fugiat molestiae tempora corporis. Sed dignissimos suscipit
								</label>
							</div>
						</div>
						<div>
							<button class="btn btn-primary">Update</button>
							<button class="btn btn-light">Cancel</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>


	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
 {% endblock%}

main/templates/userprofile/photo_list.html
{% extends 'userprofile/profile.html' %}
{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Album</h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    {% for photo in photos %}
      <div class="col-sm-4 col-md-3">
        <img src="{{ photo.file.url }}" class="thumbnail">
      </div>
    {% endfor %}
  </div>

{% endblock %}

main/templates/userprofile/profile.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.js" ></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.css"  />
    
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
         {% load static%}   

  {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cropper/1.0.1/jquery-cropper.min.js" integrity="sha512-V8cSoC5qfk40d43a+VhrTEPf8G9dfWlEJgvLSiq2T2BmgGRmZzB8dGe7XAABQrWj3sEfrR5xjYICTY4eJr76QQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> {% endcomment %}

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% comment %} <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"> {% endcomment %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">




<link href="{% static 'main/cropper.min.css' %}" rel="stylesheet">

    <script src="{% static 'main/jquery-cropper.min.js' %}"></script>







  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    
    {% block javascript %}
    {% endblock %}
  </body>
</html>